---
- name: Create manifests backup dir
  file:
    path: "{{ kube_manifests_backup_dir }}"
    state: directory
    mode: '0766'
- name: Move files out of manifests dir
  copy:
    remote_src: true
    src: "{{ item }}"
    dest: "{{ kube_manifests_backup_dir }}"
  loop: "{{ files_list_dict[ inventory_hostname ] }}"
#- name: Debug loop 1
#  debug:
#    msg: Printing backup filepath "{{ kube_manifests_backup_dir }}/{{ item | basename }}
#  loop: "{{ files_list_dict[ inventory_hostname ] }}"
- name: Debug get stopped pod
  shell:
    cmd: sudo crictl ps --state exited
  register: results

- name: Debug print pod results
  debug:
    msg: "{{ results }}"
