---
- name: Backup phase - creating manifests backup dir
  file:
    path: "{{ kube_manifests_backup_dir }}"
    state: directory
    mode: '0766'
  tags: backup
- name: Backup phase - backup manifests files to {{ kube_manifests_backup_dir }}
  copy:
    remote_src: true
    src: "{{ item }}"
    dest: "{{ kube_manifests_backup_dir }}"
  loop: "{{ files_list_dict[ inventory_hostname ] }}"
  tags: backup