---
- name: Create manifests backup dir
  file:
    path: "{{ kube_manifests_backup_dir }}"
    state: directory
    mode: '0766'
- name: Move files out of manifests dir
  copy:
    remote_src: true
    src: "{{ item }}"
    dest: "{{ kube_manifests_backup_dir }}"
  loop: "{{ files_list_dict[ inventory_hostname ] }}"
#- name: Debug loop 1
#  debug:
#    msg: Printing backup filepath "{{ kube_manifests_backup_dir }}/{{ item | basename }}
#  loop: "{{ files_list_dict[ inventory_hostname ] }}"
#- name: Get stopped pods
#    shell:
#      cmd: sudo crictl ps --state exited -q
#    register: results
#    until: results.stdout.find('6e3077f5bf834c2e748002969ebec568f4936104355ceef2524c51350ddee7f0abcd') != -1
#    retries: 30
#    delay: 5
#  - name: Stopped pods list of ids
#    set_fact:
#      stopped_pods: "{{ results.stdout | split('\n') }}"
#  - name: Debug print pod results
#    debug:
#      msg: "{{ stopped_pods }}"
