---
- name: Init phase block
  tags: init
  block:
  - name: Init phase - set fact files_list_dict
    set_fact:
      files_list_dict: {}

  - name: Init phase - set fact host files_list_dict
    set_fact:
      files_list_dict: "{{ files_list_dict | combine( { inventory_hostname: [] } ) }}"

  - name: Init phase - setting source manifests path
    set_fact:
      manifest_src_dir: "{{ kube_manifests_dir }}"
    when: (backup is defined) and (backup | bool)

  - name: Init phase - setting source manifests path
    set_fact:
      manifest_src_dir: "{{ kube_manifests_backup_dir }}"
    when: (startcp is defined) and (startcp | bool)

  - name: Init phase - collecting static manifest files
    find:
      path: "{{ manifest_src_dir }}"
    register: manifests

  - name: Init phase - appending manifests to files_list_dict
    set_fact:
      files_list_dict: "{{ files_list_dict | combine( { inventory_hostname: files_list_dict[inventory_hostname] + [item.path] }) }}"
    loop: "{{ manifests.files }}"
    loop_control:
      label: "{{ item.path }}"