---
- name: CRI block
  tags: debug
  block:
  - name: Get container runtime
    shell:
      cmd: "kubectl get nodes {{ inventory_hostname }} -o jsonpath='{$.status.nodeInfo.containerRuntimeVersion}'"
    register: cri_full

  - name: Debug print
    debug:
      msg: cri name '{{ cri_full.stdout_lines[0] }}'

  - name: Get cri base name
    set_fact:
      cri: '{{ cri_full.stdout_lines[0].split(":")[0] | trim }}'

  - name: Debug print 2
    debug:
      msg: basename '{{ cri }}'

# docker container ls -f name="k8s_POD_kube-apiserver-babka-1-p8vx5hwmx97xrpg"
- name: Docker calls test block
  tags: debug
  block:
  - name: set container name for debug
    set_fact:
      container_name: 'k8s_POD_kube-controller-manager-{{ inventory_hostname }}'
  - name: get container ID
    shell:
      cmd: 'docker container ls -f name={{ container_name }} -q'
    register: container_id
  - name: debug print container_id
    debug:
      msg: cmd_out '{{ container_id.stdout_lines[0] }}'
- name: Debug test block
  tags: debug
  block:
  - name: block debug print
    debug:
      msg: Test debug print for block
  when: (container_id is not defined)
