---
- name: Restart phase - etcd health check block
  tags: etcdhealth
  block:
    - name: Restart phase - checking etcd cluster endpoint health
      tags: debug
      shell:
        cmd: /usr/local/bin/etcdctl.sh endpoint health -w json
      register: etcd_h_json
      until: etcd_h_json.stdout_lines[0] | from_json | selectattr('health','equalto', false) | list | count == 0
      retries: 30
      delay: 5
  always:
    - name: Restart phase - etcd health check status
      debug:
        msg: etcd health "{{ item }}"
      loop: "{{ etcd_h_json.stdout_lines[0] }}"
      loop_control:
        label: "{{ item.endpoint }}"

#
#- name: Restart phase - etcd health block
#  tags: etcdhealth
#  block:
#  - name: Restart phase - getting etcd cluster health
#    shell:
#      cmd: /usr/local/bin/etcdctl.sh endpoint health -w json
#    register: etcd_h_json
#
#  - name: Restart phase - verifying etcd cluster health by node
#    debug:
#      msg: "{{ item }}"
#    failed_when: item.health != true
#    loop: "{{ etcd_h_json.stdout_lines[0] }}"
