---
- name: Restart phase - etcd health check block
  tags: etcdhealth
  block:
    - name: Restart phase - checking etcd cluster endpoint health
      shell:
        cmd: /usr/local/bin/etcdctl.sh endpoint health -w json
      register: etcd_h_json
      until: etcd_h_json.stdout_lines[0] | from_json | selectattr('health','equalto', false) | list | count == 0
      retries: 30
      delay: 5

#     - name: Restart phase - set etcd health fact
#       set_fact:
#         etcd_healthy: true
#         cacheable: yes
  when: (etcd_healthy is undefined) or (etcd_healthy == false)
  rescue:
  - name: Restart phase - set etcd health fact
      set_fact:
        etcd_healthy: false

  always:
    - name: Restart phase - etcd health check status
      debug:
        msg: etcd health "{{ item }}"
      loop: "{{ etcd_h_json.stdout_lines[0] }}"
      loop_control:
        label: "{{ item.endpoint }}"
