---
- name: Restart pshase - getting etcd cluster health
  shell:
    cmd: /usr/local/bin/etcdctl.sh endpoint health -w json
  register: etcd_h_json
  run_once: true

- name: Restart phase - verifying etcd cluster health by node
  debug:
    msg: "{{ item }}"
  failed_when: item.health != true
  loop: "{{ etcd_h_json.stdout_lines[0] }}"
  run_once: true