---
- name: Restart phase etcd - etcd health check block
  tags: etcdhealth
  block:
  - name: Restart phase etcd - checking etcd cluster endpoint health
    shell:
      cmd: "{{ etcdctl_sh }} endpoint health -w json"
    register: etcd_h_json
    until: etcd_h_json.stdout_lines[0] | from_json | selectattr('health','equalto', false) | list | count == 0
    retries: "{{ retry_count }}"
    delay: "{{ retry_delay }}"

  when: (etcd_healthy is undefined) or (etcd_healthy == false)
  rescue:
  - name: Restart phase etcd - setting etcd_healthy fact false
    set_fact:
      etcd_healthy: false

  always:
  - name: Restart phase etcd - etcd health check status
    debug:
      msg: etcd health "{{ item }}"
    loop: "{{ etcd_h_json.stdout_lines[0] }}"
    loop_control:
      label: "{{ item.endpoint }}"
