---
#- name: Debug print etcd path
#  debug:
#    msg: etcd path "{{ kube_manifests_backup_dir }}/{{ etcd_manifest | basename }}"
- name: Restart phase - etcd restart block
  tags: startetcd
  block:
  - name: Restart phase - restoring etcd manifest to {{ kube_manifests_dir }}
    copy:
      remote_src: true
      src: "{{ kube_manifests_backup_dir }}/{{ etcd_manifest | basename }}"
      dest: "{{ kube_manifests_dir }}"

  - name: Restart phase - getting pod ready status for {{ etcd_pod_name }}
    shell:
      cmd: sudo crictl pods --name ^{{ etcd_pod_name }}$ --state ready -q
    register: result
    until: "result is not failed"
    retries: 10
    delay: 5
    changed_when: result.stdout_lines[0]

  - name: Restart phase - setting etcd_restarted fact
    set_fact:
        etcd_restarted: true
    when: "result is not failed"