---
- name: Geting CRI socket from host
  tags: getcri
  block:
  - name: CRI - Getting kubelet cmdline from proc
    shell:
      cmd: tr \\0 ' ' < /proc/"$(pgrep kubelet)"/cmdline
    register: kubelet_cmd

  - name: CRI - Getting CRI socket name
    set_fact:
      cri: "{{ (kubelet_cmd.stdout_lines[0] | regex_search('--container-runtime-endpoint=(\/\\w+){1,}')).split('=')[1].split('/')[3] | trim }}"

  - name: CRI
    debug:
      msg: Detected CRI {{ cri }}