---
- name: Geting CRI socket from host
  tags: getcri
  block:
  - name: CRI - Getting container runtime from nodeInfo
    shell:
      cmd: "kubectl get nodes {{ inventory_hostname }} -o jsonpath='{$.status.nodeInfo.containerRuntimeVersion}'"
    register: cri_full

  - name: CRI - Getting CRI basename
    set_fact:
      cri: '{{ cri_full.stdout_lines[0].split(":")[0] | trim }}'
    failed_when: cri not in ['containerd', 'docker']

  - name: CRI
    debug:
      msg: Detected CRI {{ cri }}

  - name: CRI - Create reference file for restore op
    copy:
      content: "{{ cri }}"
      dest: "{{ cri_reference }}"
      force: true
  when: ((stopcp is defined) and (stopcp|bool))

- name: Getting CRI from reference file for restore op
  tags: getcri
  block:
  - name: CRI - Read from cri reference file
    set_fact:
      cri: "{{ lookup('file', cri_reference) }}"
  when: ((startcp is defined) and (startcp|bool)) or ((startetcd is defined) and (startetcd|bool)) or ((stopetcd is defined) and (stopetcd|bool))
