---
- name: Geting CRI socket from host
  tags: getcri
  block:
  - name: CRI - Getting kubelet cmdline from proc
    shell:
      cmd: tr \\0 ' ' < /proc/"$(pgrep kubelet)"/cmdline
    register: kubelet_cmd

  - name: CRI - Getting CRI socket name
    set_fact:
      cri: "{{ (kubelet_cmd | regex_search('--container-runtime-endpoint=[(\\w\\/)+]\\s')).split('=')[1].split('/')[3] | trim }}"

  - name: CRI - debug print
    debug:
      msg: CRI "{{ cri }}"