---
- name: Geting CRI socket from host
  tags: getcri
  block:
  - name: CRI - Getting container runtime from nodeInfo
    shell:
      cmd: "kubectl get nodes {{ inventory_hostname }} -o jsonpath='{$.status.nodeInfo.containerRuntimeVersion}'"
    register: kubelet_cmd

  - name: CRI - Getting CRI basename
    set_fact:
      cri: '{{ cri_full.stdout_lines[0].split(":")[0] | trim }}'
    failed_when: cri not in ['containerd', 'docker']

  - name: CRI
    debug:
      msg: Detected CRI {{ cri }}