---
- name: Kubernetes pods state check block
  tags: k8shealth
  block:
  - name: DEBUG PAUSE
    pause:
      seconds: 60
  - name: Kubernetes health - verify all pods are running in kube-system namespace
    shell:
      cmd: "kubectl get pods -n kube-system -o jsonpath='{.items[?(@.status.containerStatuses[*].ready==false)]}'|jq .metadata.name|tr -d '\"'"
    register: pods
    until:  pods.stdout_lines|length == 0
    retries: '{{ retry_count }}'
    delay: '{{ retry_delay }}'
  - name: Kubernetes health - all pods are running in kube-system namespace
    debug:
      msg: 'ALL PODS ARE RUNNING IN KUBE-SYSTEM'
    when: pods.stdout_lines|length == 0
  rescue:
  - name: Kubernetes health - pods found not running in kube-system namespace
    debug:
      msg: 'pods not running: {{ pods.stdout_lines }}'
    when: pods.stdout_lines|length > 0

#     k get pods -o jsonpath='{.items[?(@.status.containerStatuses[*].ready==false)]}'