---
- name: Kubernetes pods state check block
  tags: k8shealth
  block:
  - name: Kubernetes health - get list of pods not running in kube-system namespace
    shell:
      cmd: "kubectl get pods -n kube-system --field-selector=status.phase!=Running -o name"
    register: pods

  - name: Kubernetes health - pods found not running in kube-system namespace
    debug:
      msg: 'PODS NOT RUNNING: {{ pods.stdout_lines }}'
    when: pods.stdout_lines|length > 0

  - name: Kubernetes health - all pods are running kube-system namespace
    debug:
      msg: 'ALL PODS ARE RUNNING IN KUBE-SYSTEM'
    when: pods.stdout_lines|length == 0