---
# tasks file for cprestart
#- name: Gather kubernetes manifests files
#  import_tasks: collect_manifests.yaml
#- name: Backup kubernetes manifests dir
#  import_tasks: backup_manifest_files.yaml
#
#- name: Stop kubernetes control plane pods
#  import_tasks: stop_control_plane_loop.yaml
#- name: Stop etcd server pods
#  import_tasks: etcd_stop.yaml
#- name: Restart etcd server pods
#  import_tasks: etcd_start.yaml
#- name: Restart kubernetes control plane pods
#  import_tasks: restart_control_plane_loop.yaml

- name: Debug etcd health
  import_tasks: etcd_health.yaml