---
# tasks file for cprestart
- name: Get CRI from host
  import_tasks: get_cri.yaml
  tags: [getcri]
  when: (getcri is defined) and (getcri | bool)

- name: Gather kubernetes manifests files
  import_tasks: collect_manifests.yaml
  tags: [init]
  when: (init is defined) and (init | bool)

- name: Backup kubernetes manifests dir
  import_tasks: backup_manifest_files.yaml
  tags: [backup]
  when: (backup is defined) and (backup | bool)

- name: Stop kubernetes control plane pods
  import_tasks: stop_control_plane_loop.yaml
  tags: [stopcp]
  when: (stopcp is defined) and (stopcp | bool)

- name: Stop etcd server pods
  import_tasks: etcd_stop.yaml
  tags: [stopetcd]
  when: (stopetcd is defined) and (stopetcd | bool)

- name: Restart etcd server pods
  import_tasks: etcd_start.yaml
  tags: [startetcd]
  when: (startetcd is defined) and (startetcd | bool)

- name: Check etcd health
  import_tasks: etcd_health.yaml
  tags: [etcdhealth]
  when: (etcdhealth is defined) and (etcdhealth | bool)

- name: Restart kubernetes control plane pods
  import_tasks: restart_control_plane_loop.yaml
  tags: [startcp]
  when: (startcp is defined) and (startcp | bool)

- name: Check kubernetes pods health in kube-system
  import_tasks: kube_pods_state.yaml
  tags: k8shealth
  when: (k8shealth is defined) and (k8shealth | bool)

- name: debug etcdhealth
  import_tasks: debug_only.yaml
  tags: [debug]
  when: (debug is defined) and (debug | bool)