---
- name: Create manifests backup dir
  file:
    path: "{{ kube_manifests_backup_dir }}"
    state: directory
    mode: '0766'
- name: Move files out of manifests dir
  copy:
    remote_src: true
    src: "{{ item }}"
    dest: "{{ kube_manifests_backup_dir }}"
  loop: "{{ files_list_dict[ inventory_hostname ] }}"
