---
- name: Restart control plane pods
  block:
  - name: Get backup path for manifest file
    set_fact:
      backup_filepath: "{{ kube_manifests_backup_dir }}/{{ item | basename }}"

  - name: Copy manifest to static pods path
    copy:
      remote_source: true
      src: "{{ backup_filepath }}"
      dest: "{{ kube_manifests_dir }}"

  - name: Read manifest file
    shell:
      cmd: "cat {{ backup_filepath }}"
    register: manifest

  - name: Get static_pod name from manifest
    set_fact:
      pod_name: "{{ manifest_yaml.metadata.name }}-{{ inventory_hostname }}"
    vars:
      manifest_yaml: "{{ manifest.stdout | from_yaml }}"

  - name: Get the ready state for pod {{ pod_name }}
    shell:
      cmd: sudo crictl pods --name ^{{ pod_name }}$ --state ready -q
    register: result
    until: "result is not failed"
    retries: 30
    delay: 5
    changed_when: result.stdout_lines[0]