---
- name: Restart phase - Restart control plane pods block
  block:
  - name: Restart phase - getting backup path for {{ item | basename }}
    set_fact:
      backup_filepath: "{{ kube_manifests_backup_dir }}/{{ item | basename }}"

  - name: Restart phase - restoring {{ item | basename }} to {{ kube_manifests_dir }}
    copy:
      remote_src: true
      src: "{{ backup_filepath }}"
      dest: "{{ kube_manifests_dir }}"

  - name: Restart phase - reading manifest file {{ item }}
    shell:
      cmd: "cat {{ item }}"
    register: manifest

  - name: Restart phase - getting static_pod name from manifest {{ item | basename }}
    set_fact:
      pod_name: "{{ manifest_yaml.metadata.name }}-{{ inventory_hostname }}"
    vars:
      manifest_yaml: "{{ manifest.stdout | from_yaml }}"

  - name: Restart phase - getting the ready state for pod {{ pod_name }}
    shell:
      cmd: sudo crictl pods --name ^{{ pod_name }}$ --state ready -q
    register: result
    until: "result is not failed"
    retries: 30
    delay: 5
    changed_when: result.stdout_lines[0]