---
- name: Stop kubernetes api and manager pods
  block:
    - name: Read manifest file
      shell:
        cmd: "cat {{ item }}"
      register: manifest

    - name: Get static_pod name from manifest
      set_fact:
        pod_name: "{{ manifest_yaml.metadata.name }}-{{ inventory_hostname }}"
      vars:
        manifest_yaml: "{{ manifest.stdout | from_yaml }}"

    - name: Stopping pod {{ pod_name }}
      file:
        path: "{{ item }}"
        state: absent

    - name: Get notready status for pod {{ pod_name }}
      shell:
        cmd: sudo crictl pods --name ^{{ pod_name }}$ --state notready -q
      register: result
      until: "result is not failed"
      retries: 10
      delay: 5
      changed_when: result.stdout_lines[0]
